export { default as Feed } from './Feed';
export { default as History } from './History';
export { default as Home } from './Home';
export { default as LikedVideos } from './LikedVideos';
export { default as Login } from './Login';
export { default as Playlists } from './Playlists';
export { default as Register } from './Register';
export { default as VideoDetail } from './VideoDetail';
export { default as WatchLater } from './WatchLater';
